name: Workflow on Readme.md

on: push

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4

  translateREADME:
    needs: generateTOC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified
        uses: DeeDive/translate-readme@main
        with:
          LANG: zh-CN
      - name: Adding README - Chinese Traditional
        uses: DeeDive/translate-readme@main
        with:
          LANG: zh-TW
      - name: Adding README - Portuguese
        uses: DeeDive/translate-readme@main
        with:
          LANG: pt
      - name: Adding README - German
        uses: DeeDive/translate-readme@main
        with:
          LANG: de
      - name: Adding README - French
        uses: DeeDive/translate-readme@main
        with:
          LANG: fr
      - name: Adding README - Japanese
        uses: DeeDive/translate-readme@main
        with:
          LANG: ja
      - name: Adding README - Spanish
        uses: DeeDive/translate-readme@main
        with:
          LANG: es
      - name: Adding README - Arabic
        uses: DeeDive/translate-readme@main
        with:
          LANG: ar
      - name: Adding README - Hindi
        uses: DeeDive/translate-readme@main
        with:
          LANG: hi
