name: Workflow on Readme.md

on: push

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4

  translateREADME:
    needs: generateTOC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified - Mandarin Chinese is the most spoken language in the world, and many universities have significant populations of Chinese students. Including Chinese in your README can help you reach these students.
        uses: DeeDive/translate-readme@main
        with:
          LANG: zh-CN
      - name: Adding README - Chinese Traditional
        uses: DeeDive/translate-readme@main
        with:
          LANG: zh-TW
      - name: Adding README - Portuguese - Portuguese is spoken in many universities in Brazil, Portugal, and other parts of the world, so it may be worth considering including it as well.
        uses: DeeDive/translate-readme@main
        with:
          LANG: pt
      - name: Adding README - German - German is widely spoken in universities in Germany, Austria, and Switzerland, so it may be relevant if you are targeting students in those countries.
        uses: DeeDive/translate-readme@main
        with:
          LANG: de
      - name: Adding README - French - French is spoken in many universities in Europe, Africa, and Canada, so including it in your README can help you reach a wider audience.
        uses: DeeDive/translate-readme@main
        with:
          LANG: fr
      - name: Adding README - Japanese
        uses: DeeDive/translate-readme@main
        with:
          LANG: ja
      - name: Adding README - Spanish - Spanish is also a good language to include as many universities have a significant population of Spanish-speaking students, especially in Latin America and Spain.
        uses: DeeDive/translate-readme@main
        with:
          LANG: es
          
